import {
  Award,
  BadgeEuro,
  Bot,
  Building2,
  ClipboardCheck,
  FileClock,
  FileSearch,
  FileText,
  FolderKanban,
  Inbox,
  LayoutDashboard,
  MailPlus,
  Radar,
  Settings,
  UserCircle,
  Users,
  Wrench,
} from "lucide-react";

/** Icônes de navigation référencées par nom (sérialisables RSC → client). */
export const NAV_ICONS = {
  dashboard: LayoutDashboard,
  tenders: FileSearch,
  company: Building2,
  documents: FileText,
  team: Users,
  equipment: Wrench,
  references: Award,
  pricing: BadgeEuro,
  profile: UserCircle,
  settings: Settings,
  clients: Building2,
  leads: Inbox,
  invitations: MailPlus,
  proposals: FolderKanban,
  validations: ClipboardCheck,
  commissions: BadgeEuro,
  expiredDocs: FileClock,
  sources: Radar,
  ai: Bot,
} as const;
